title: Programavimo kalba Java
description: VK EIF Lekt. Marius G탑ego탑evskis
show_downloads: true

baseurl: "/Java-Lecture-Notes" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://eif-courses.github.io/" # change this to the base hostname & protocol for your site

google_analytics:
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: "Marius G탑ego탑evskis"

# pagination
paginate: 5 # amount of posts to show
paginate_path: /page:num/
